before_install:
  - sudo add-apt-repository ppa:gviz-adm/graphviz-dev -y
  - sudo apt-get update -qq
  - sudo apt-get remove libcdt4
  - sudo apt-get remove libpathplan4
  - sudo apt-get -y install graphviz

script: make
